#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Feb  9 21:20:30 2020

@author: mariusz
"""

num = int(input("Wpisz liczbę: "))

if num < 0:
    isNeg = True
    num = abs(num)
else: 
    isNeg = False

result = ''
if num == 0:
    result = "0"
while num > 0:
    result = str(num%2)+result #reszta z dzielenia  przez 2
    num = num//2  #dzielenie całkowite przez 2
if isNeg:
    result ="-" + result
    
print(result)
    